spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/melorour?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  rabbitmq:
    host: 139.199.119.69
    port: 5672
    username: guest
    password: guest 
server:
  port: 8082
  
env:
  test333335555545
